name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag (optional)'
        required: false
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Ensure package is ready for pushing
      - name: Prepare package for push
        if: github.event_name != 'pull_request'
        run: |
          echo "Preparing package for push..."
          echo "Package: ${{ github.event.repository.name }}"
          echo "Repository: ${{ github.repository }}"
          echo "This step ensures the package is ready for Docker push"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from package.json
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Get commit hash
        id: commit
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "commit=$COMMIT_HASH" >> $GITHUB_OUTPUT
          echo "Commit: $COMMIT_HASH"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.package-version.outputs.version }}
            ghcr.io/${{ github.repository }}:${{ steps.commit.outputs.commit }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Build summary
        if: github.event_name != 'pull_request'
        run: |
          echo "## Docker Image Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Repository:** ghcr.io/${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Version:** ${{ steps.package-version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** ${{ steps.commit.outputs.commit }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Platforms:** linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY
          echo "- **Tags:**" >> $GITHUB_STEP_SUMMARY
          echo "  - ghcr.io/${{ github.repository }}:latest" >> $GITHUB_STEP_SUMMARY
          echo "  - ghcr.io/${{ github.repository }}:${{ steps.package-version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "  - ghcr.io/${{ github.repository }}:${{ steps.commit.outputs.commit }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Image successfully built and pushed to GHCR!" >> $GITHUB_STEP_SUMMARY

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Docker Build Summary
            
            **Build completed successfully!**
            
            - **Repository:** ghcr.io/${{ github.repository }}
            - **Version:** ${{ steps.package-version.outputs.version }}
            - **Commit:** ${{ steps.commit.outputs.commit }}
            - **Platforms:** linux/amd64, linux/arm64
            
            The image was built but not pushed (PR builds are for testing only).
            
            To deploy, merge this PR or create a release tag.`
            })
